---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-hpa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-hpa
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: web
        image: spring-boot-hpa
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        ports:
          - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hpa
spec:
  ports:
  - nodePort: 32000
    port: 80
    targetPort: 8080
  selector:
    app: spring-boot-hpa
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: web
        image: redis
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis