redisUrl: ${REDIS_URL:redis://localhost:6379}
mainQueueName: ${MAIN_QUEUE:mainQueue}
workerQueueName: ${HOSTNAME:worker1}
server:
  address: 0.0.0.0
storeEnabled: ${STORE_ENABLED:true}
workerEnabled: ${WORKER_ENABLED:true}